### ISSUE TITLE
how to build and compile branch:70-sdk

### ISSUE THREAD

**Issue by tianwen2976** [open-webrtc-toolkit/owt-deps-webrtc#12]
As above, how to success  build and compile 70-sdk, can someone guide me?

**Comment by JamesTerm** [comment]
This gets built automatically per instruction from here:
https://github.com/open-webrtc-toolkit/owt-client-native

gclient sync... will provide this sdk as a part of its sdk.  What I do than is I take that source and put link it to this SDK (well actually a forked repo, so I can make local changes).

I hope this helps

**Comment by tianwen2976** [comment]
thank you @JamesTerm
