### ISSUE TITLE
DISABLE_H265 would read better as RTC_ENABLE_H265

### ISSUE THREAD

**Issue by youennf** [open-webrtc-toolkit/owt-deps-webrtc#48]
Instead of #ifndef DISABLE_H265, it might be more convenient to write #if defined(RTC_ENABLE_H265)

**Comment by jianjunz** [comment]
Agreed. There are two macros indicate whether HEVC is enabled, `DISABLE_H265` and `OWT_ENABLE_H265`. I'm planning to remove `DISABLE_H265` in the near future. Prefix `RTC_` may conflict with macros defined by libwebrtc and Chromium. So I would prefer `OWT_ENABLE_H265` at this moment.

**Comment by JamesTerm** [comment]
@jianjunz   That's how I do it... I write the feature as a disabled macro, and then later plan to remove the macro once it has been tested well enough to not break others.  Doing it this way keeps the macro defined count to a minimum.
